name: mineru
channels:
  - defaults
  - conda-forge
dependencies:
  - httpx
  - langchain-text-splitters
  - langgraph-checkpoint
  - langgraph-sdk
  - pillow
  - pip
  - pre-commit
  - python=3.10
  - pyyaml
  - requests
  - requests-toolbelt
  - setuptools
  - sqlalchemy
  - typing_extensions
  - virtualenv
  - weasyprint
  - wheel
  - pip:
      - accelerate
      - aiofiles
      - albumentations
      - annotated-doc
      - av
      - beautifulsoup4
      - boto3
      - chromadb
      - click
      - colorlog
      - cupy-cuda12x
      - doclayout-yolo
      - einops
      - email-validator
      - fastapi
      - gradio
      - gradio-client
      - gradio-pdf
      - huggingface-hub
      - json-repair
      - kubernetes
      - langchain
      - langchain-chroma
      - langchain-community
      - langchain-core
      - langgraph
      - langgraph-prebuilt
      - langsmith
      - loguru
      - magika
      - mineru
      - mineru-vl-utils
      - mistral-common
      - modelscope
      - numpy
      - nvidia-cublas-cu12
      - nvidia-cuda-cupti-cu12
      - nvidia-cuda-nvrtc-cu12
      - nvidia-cuda-runtime-cu12
      - nvidia-cudnn-cu12
      - nvidia-cufft-cu12
      - nvidia-curand-cu12
      - nvidia-cusolver-cu12
      - nvidia-cusparse-cu12
      - nvidia-nccl-cu12
      - nvidia-nvjitlink-cu12
      - nvidia-nvtx-cu12
      - ollama
      - onnxruntime
      - openai
      - opencv-python
      - orjson
      - pandas
      - pdfminer-six
      - pdftext
      - polars
      - prometheus-client
      - prometheus-fastapi-instrumentator
      - protobuf
      - psutil
      - pydantic
      - pydantic-settings
      - pypdf
      - pypdfium2
      - python-dotenv
      - python-multipart
      - ray
      - reportlab
      - rich
      - ruff
      - safetensors
      - scikit-image
      - scipy
      - sentencepiece
      - shapely
      - starlette
      - tenacity
      - tiktoken
      - torch
      - torchaudio
      - torchvision
      - tqdm
      - transformers
      - triton
      - typer
      - ultralytics
      - uvicorn
      - vllm
      - xformers
